### ISSUE TITLE
while running main.py I get: "RuntimeError: Expected all tensors to be on the same device, but found at least two devices"

### ISSUE THREAD

**Issue by illtellyoulater** [rinongal/textual_inversion#9] opened 2022-08-24 21:36 UTC
Hi I am launching main.py with this line:

`python.exe .\main.py --base configs/stable-diffusion/v1-finetune.yaml -t --actual_resume .\sd-v1-4.ckpt -n my-model --gpus=0, --data_root my-folder --init_word mytestword`

and I get up to this point:

```
  | Name              | Type               | Params
---------------------------------------------------------
0 | model             | DiffusionWrapper   | 859 M
1 | first_stage_model | AutoencoderKL      | 83.7 M
2 | cond_stage_model  | FrozenCLIPEmbedder | 123 M
3 | embedding_manager | EmbeddingManager   | 1.5 K
---------------------------------------------------------
768       Trainable params
1.1 B     Non-trainable params
1.1 B     Total params
4,264.947 Total estimated model params size (MB)
Validation sanity check:   0%|                                                        | 0/2 [00:00<?, ?it/s]
Summoning checkpoint.
```

but after a while it stops with this error:

`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper__index_select)`

Do you know what may cause it?

**Comment by rinongal** [comment] 2022-08-24 21:46
Can you post the full error? And did you modify any code? It looks like its trying to run some operation that involves a tensor that did not get properly moved to the CPU.

I'm guessing it's somewhere in the embedding manager, but will need the full trace to see where.

**Comment by hlky** [comment] 2022-08-24 22:54
Same error, using nicolai256/Stable-textual-inversion_win fork if it makes any difference

`
Traceback (most recent call last):
  File "main.py", line 783, in <module>
    trainer.fit(model, data)
  File "C:\Users\user\.conda\envs\sti\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "C:\Users\user\.conda\envs\sti\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\user\.conda\envs\sti\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "C:\Users\user\.conda\envs\sti\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1199, in _run
    self._dispatch()
  File "C:\Users\user\.conda\envs\sti\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "C:\Users\user\.conda\envs\sti\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "C:\Users\user\.conda\envs\sti\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1289, in run_stage
    return self._run_train()
  File "C:\Users\user\.conda\envs\sti\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1311, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "C:\Users\user\.conda\envs\sti\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1375, in _run_sanity_check
    self._evaluation_loop.run()
  File "C:\Users\user\.conda\envs\sti\lib\site-packages\pytorch_lightning\loops\base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "C:\Users\user\.conda\envs\sti\lib\site-packages\pytorch_lightning\loops\dataloader\evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(dataloader, dataloader_idx, dl_max_batches, self.num_dataloaders)
  File "C:\Users\user\.conda\envs\sti\lib\site-packages\pytorch_lightning\loops\base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "C:\Users\user\.conda\envs\sti\lib\site-packages\pytorch_lightning\loops\epoch\evaluation_epoch_loop.py", line 122, in advance
    output = self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "C:\Users\user\.conda\envs\sti\lib\site-packages\pytorch_lightning\loops\epoch\evaluation_epoch_loop.py", line 217, in _evaluation_step
    output = self.trainer.accelerator.validation_step(step_kwargs)
  File "C:\Users\user\.conda\envs\sti\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 236, in validation_step
    return self.training_type_plugin.validation_step(*step_kwargs.values())
  File "C:\Users\user\.conda\envs\sti\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 219, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "C:\Users\user\.conda\envs\sti\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "S:\ai\Stable-textual-inversion_win\ldm\models\diffusion\ddpm.py", line 363, in validation_step
    _, loss_dict_no_ema = self.shared_step(batch)
  File "S:\ai\Stable-textual-inversion_win\ldm\models\diffusion\ddpm.py", line 903, in shared_step
    loss = self(x, c)
  File "C:\Users\user\.conda\envs\sti\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "S:\ai\Stable-textual-inversion_win\ldm\models\diffusion\ddpm.py", line 911, in forward
    c = self.get_learned_conditioning(c)
  File "S:\ai\Stable-textual-inversion_win\ldm\models\diffusion\ddpm.py", line 590, in get_learned_conditioning
    c = self.cond_stage_model.encode(c, embedding_manager=self.embedding_manager)
  File "S:\ai\Stable-textual-inversion_win\ldm\modules\encoders\modules.py", line 325, in encode
    return self(text, **kwargs)
  File "C:\Users\user\.conda\envs\sti\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "S:\ai\Stable-textual-inversion_win\ldm\modules\encoders\modules.py", line 320, in forward
    z = self.transformer(input_ids=tokens, **kwargs)
  File "C:\Users\user\.conda\envs\sti\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "S:\ai\Stable-textual-inversion_win\ldm\modules\encoders\modules.py", line 298, in transformer_forward
    return self.text_model(
  File "C:\Users\user\.conda\envs\sti\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "S:\ai\Stable-textual-inversion_win\ldm\modules\encoders\modules.py", line 259, in text_encoder_forward
    hidden_states = self.embeddings(input_ids=input_ids, position_ids=position_ids, embedding_manager=embedding_manager)
  File "C:\Users\user\.conda\envs\sti\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "S:\ai\Stable-textual-inversion_win\ldm\modules\encoders\modules.py", line 181, in embedding_forward
    inputs_embeds = self.token_embedding(input_ids)
  File "C:\Users\user\.conda\envs\sti\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\user\.conda\envs\sti\lib\site-packages\torch\nn\modules\sparse.py", line 158, in forward
    return F.embedding(
  File "C:\Users\user\.conda\envs\sti\lib\site-packages\torch\nn\functional.py", line 2044, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper__index_select)
`

**Comment by hlky** [comment] 2022-08-25 00:41
@illtellyoulater @rinongal Fixed on my end with

```
pip install -e .
```

**Comment by XodrocSO** [comment] 2022-08-25 05:55
@illtellyoulater 

Try `--gpus 1` instead?

**Comment by rinongal** [comment] 2022-08-25 09:56
This is a bit of a tough one. I can't seem to reproduce this locally, and it's failing before reaching our new embedding step.

It seems like either the tokenizer outputs or the embedding models are not being properly moved to the GPU.

Could you try printing the device of the token embedder (with something like print(next(self.token_embedding.parameters()).device)) and the device of the input_ids (print(input_ids.device)) before line 181 in modules.py and letting me know what you get?

**Comment by rinongal** [comment] 2022-09-07 11:35
Closing due to lack of activity. Feel free to reopen if you still need help.

**Closed by rinongal** 2022-09-07 11:35 UTC

**Comment by illtellyoulater** [comment] 2022-09-10 13:47
@rinongal apologies for my late reply and for making you waste some extra time on this! In the end the problem was easier than expected and I managed to make it work following @XodrocSO advice to use `--gpus 1`. Not sure why I had to use that though since all other libs and scripts always see my GPU as 0. Anyway what matters is now it works, so thank you all :)
Btw, how many epochs I should train for? Or what loss amount should I aim at?

This is my current output:

`Epoch 3:  83%|▊| 335/404 [06:48<01:23,  1.22s/it, loss=0.17, v_num=0, train/loss_simple_step=0.00639, train/loss_vlb_step=3.34e-5, train/loss_step=0.00639, global_step=1534.0, train/loss_simpl`

**Comment by rinongal** [comment] 2022-09-10 17:47
If you had to use `--gpus 1` you're probably using one of the forks that modified the command to list the number of GPUs, rather than their indices.

It's less a matter of epochs and more of training steps. We used 5k steps in the paper, with a batch size of 4 and 2 GPUs, regardless of the dataset size.

If you're using smaller batches you might want to turn on gradient accumulation, or use more steps.

**Comment by EladNoy** [comment] 2022-09-14 19:41
I'm getting the same problem

Using 
`python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n try4 --gpus 0 --data_root MY_input_images/Object1/ --init_word plane --placeholder_tokens "*"`

I'm getting -

```
Validation sanity check:   0%|                                                                   | 0/2 [00:00<?, ?it/s]Summoning checkpoint.

Traceback (most recent call last):
  File "main.py", line 814, in <module>
    trainer.fit(model, data)
  File "H:\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "H:\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "H:\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "H:\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1199, in _run
    self._dispatch()
  File "H:\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "H:\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "H:\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1289, in run_stage
    return self._run_train()
  File "H:\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1311, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "H:\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1375, in _run_sanity_check
    self._evaluation_loop.run()
  File "H:\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\loops\base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "H:\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\loops\dataloader\evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(dataloader, dataloader_idx, dl_max_batches, self.num_dataloaders)
  File "H:\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\loops\base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "H:\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\loops\epoch\evaluation_epoch_loop.py", line 122, in advance
    output = self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "H:\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\loops\epoch\evaluation_epoch_loop.py", line 217, in _evaluation_step
    output = self.trainer.accelerator.validation_step(step_kwargs)
  File "H:\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 236, in validation_step
    return self.training_type_plugin.validation_step(*step_kwargs.values())
  File "H:\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 219, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "H:\anaconda3\envs\ldm\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "H:\Users\User\PycharmProjects\Art\textual_inversion\ldm\models\diffusion\ddpm.py", line 368, in validation_step
    _, loss_dict_no_ema = self.shared_step(batch)
  File "H:\Users\User\PycharmProjects\Art\textual_inversion\ldm\models\diffusion\ddpm.py", line 907, in shared_step
    loss = self(x, c)
  File "H:\anaconda3\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Users\User\PycharmProjects\Art\textual_inversion\ldm\models\diffusion\ddpm.py", line 915, in forward
    c = self.get_learned_conditioning(c)
  File "H:\Users\User\PycharmProjects\Art\textual_inversion\ldm\models\diffusion\ddpm.py", line 594, in get_learned_conditioning
    c = self.cond_stage_model.encode(c, embedding_manager=self.embedding_manager)
  File "H:\Users\User\PycharmProjects\Art\textual_inversion\ldm\modules\encoders\modules.py", line 124, in encode
    return self(text, **kwargs)
  File "H:\anaconda3\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Users\User\PycharmProjects\Art\textual_inversion\ldm\modules\encoders\modules.py", line 119, in forward
    z = self.transformer(tokens, return_embeddings=True, embedding_manager=embedding_manager)
  File "H:\anaconda3\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Users\User\PycharmProjects\Art\textual_inversion\ldm\modules\x_transformer.py", line 612, in forward
    embedded_x = self.token_emb(x)
  File "H:\anaconda3\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\anaconda3\envs\ldm\lib\site-packages\torch\nn\modules\sparse.py", line 158, in forward
    return F.embedding(
  File "H:\anaconda3\envs\ldm\lib\site-packages\torch\nn\functional.py", line 2044, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper__index_select)

```

Notes
 - running windows 10 (used the recommended changes to allow it to run in this environment)
 - reduced batch size and workers to 1 via .yaml   
- Actually proceeded all the way to epoch 12 and crashed one time, now stuck at this error.
- tried `pip install -e .`, no joy.

**Comment by illtellyoulater** [comment] 2022-09-14 22:33
> If you had to use `--gpus 1` you're probably using one of the forks that modified the command to list the number of GPUs, rather than their indices.

Good catch @rinongal, that was the case!

**Comment by rinongal** [comment] 2022-09-16 07:19
@EladNoy The problem is likely in the ``--gpus 0`` part of the command. If you're using this repository, you need to use: ``--gpus 0,`` (**with** the trailing comma!). If you're using one of the windows forks, you may need to use  ``--gpus 1``.

**Comment by EladNoy** [comment] 2022-09-16 12:38
> @EladNoy The problem is likely in the `--gpus 0` part of the command. If you're using this repository, you need to use: `--gpus 0,` (**with** the trailing comma!). If you're using one of the windows forks, you may need to use `--gpus 1`.

I'm not using a fork but rather this code with some changes to circumvent Windows specific problems - but anyway, this did the trick.

I'm now reaching 
```
Epoch 11: 100%|█| 505/505 [05:23<00:00,  1.56it/s, loss=0.195, v_num=0, train/loss_simple_step=0.135, train/loss_vlb_stAverage Epoch time: 323.18 seconds
Average Peak memory 6795.34MiB
Epoch 12:   0%| | 0/505 [00:00<?, ?it/s, loss=0.195, v_num=0, train/loss_simple_step=0.135, train/loss_vlb_step=0.00045pop from empty list
Data shape for DDIM sampling is (1, 4, 32, 32), eta 1.0
Running DDIM Sampling with 200 timesteps
DDIM Sampler: 100%|██████████████████████████████████████████████████████████████████| 200/200 [00:23<00:00,  8.51it/s]
Data shape for DDIM sampling is (1, 4, 32, 32), eta 1.0██████████████████████████████| 200/200 [00:23<00:00,  8.58it/s]
Running DDIM Sampling with 200 timesteps
DDIM Sampler: 100%|██████████████████████████████████████████████████████████████████| 200/200 [00:33<00:00,  5.99it/s]
Epoch 12:  20%|▏| 100/505 [01:51<07:33,  1.12s/it, loss=0.18, v_num=0, train/loss_simple_step=0.540, train/loss_vlb_steAverage Epoch time: 112.02 seconds
Average Peak memory 6795.34MiB
Epoch 12:  20%|▏| 101/505 [01:52<07:28,  1.11s/it, loss=0.18, v_num=0, train/loss_simple_step=0.540, train/loss_vlb_ste
Saving latest checkpoint...

Traceback (most recent call last):
  File "main.py", line 819, in <module>
    trainer.test(model, data)
  File "H:\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 911, in test
    return self._call_and_handle_interrupt(self._test_impl, model, dataloaders, ckpt_path, verbose, datamodule)
  File "H:\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "H:\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 954, in _test_impl
    results = self._run(model, ckpt_path=self.tested_ckpt_path)
  File "H:\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1128, in _run
    verify_loop_configurations(self)
  File "H:\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\configuration_validator.py", line 42, in verify_loop_configurations
    __verify_eval_loop_configuration(trainer, model, "test")
  File "H:\anaconda3\envs\ldm\lib\site-packages\pytorch_lightning\trainer\configuration_validator.py", line 186, in __verify_eval_loop_configuration
    raise MisconfigurationException(f"No `{loader_name}()` method defined to run `Trainer.{trainer_method}`.")
pytorch_lightning.utilities.exceptions.MisconfigurationException: No `test_dataloader()` method defined to run `Trainer.test`.
```

But I assume this is the correct ending as per 
https://github.com/rinongal/textual_inversion/issues/36

**Comment by Baquara** [comment] 2022-09-21 06:24
Hello,

I am a Linux user, I am using this repository and I am facing the same issue. None of the solutions above worked on my end.

I execute the training with the following:

```

python main.py --base configs/stable-diffusion/v1-nr-finetune-nerd-256.yaml \
--train --actual_resume '/home/privateserver/STABLE DIFFUSION/model.ckpt' \
--name nr-256\
--gpus 0, \
--data_root $DATASET \
--seed 45 \
--no-test \
```


It then outputs this error:


```
Traceback (most recent call last):
  File "main.py", line 805, in <module>
    trainer.fit(model, data)
  File "/home/privateserver/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "/home/privateserver/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/privateserver/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/privateserver/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/home/privateserver/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/home/privateserver/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/home/privateserver/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1289, in run_stage
    return self._run_train()
  File "/home/privateserver/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1311, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "/home/privateserver/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1375, in _run_sanity_check
    self._evaluation_loop.run()
  File "/home/privateserver/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/privateserver/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(dataloader, dataloader_idx, dl_max_batches, self.num_dataloaders)
  File "/home/privateserver/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/privateserver/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 122, in advance
    output = self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "/home/privateserver/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 217, in _evaluation_step
    output = self.trainer.accelerator.validation_step(step_kwargs)
  File "/home/privateserver/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 236, in validation_step
    return self.training_type_plugin.validation_step(*step_kwargs.values())
  File "/home/privateserver/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 219, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/privateserver/.conda/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/privateserver/textual_inversion/ldm/models/diffusion/ddpm.py", line 368, in validation_step
    _, loss_dict_no_ema = self.shared_step(batch)
  File "/home/privateserver/textual_inversion/ldm/models/diffusion/ddpm.py", line 907, in shared_step
    loss = self(x, c)
  File "/home/privateserver/.conda/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/privateserver/textual_inversion/ldm/models/diffusion/ddpm.py", line 915, in forward
    c = self.get_learned_conditioning(c)
  File "/home/privateserver/textual_inversion/ldm/models/diffusion/ddpm.py", line 594, in get_learned_conditioning
    c = self.cond_stage_model.encode(c, embedding_manager=self.embedding_manager)
  File "/home/privateserver/textual_inversion/ldm/modules/encoders/modules.py", line 324, in encode
    return self(text, **kwargs)
  File "/home/privateserver/.conda/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/privateserver/textual_inversion/ldm/modules/encoders/modules.py", line 319, in forward
    z = self.transformer(input_ids=tokens, **kwargs)
  File "/home/privateserver/.conda/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/privateserver/textual_inversion/ldm/modules/encoders/modules.py", line 297, in transformer_forward
    return self.text_model(
  File "/home/privateserver/.conda/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/privateserver/textual_inversion/ldm/modules/encoders/modules.py", line 258, in text_encoder_forward
    hidden_states = self.embeddings(input_ids=input_ids, position_ids=position_ids, embedding_manager=embedding_manager)
  File "/home/privateserver/.conda/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/privateserver/textual_inversion/ldm/modules/encoders/modules.py", line 180, in embedding_forward
    inputs_embeds = self.token_embedding(input_ids)
  File "/home/privateserver/.conda/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/privateserver/.conda/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "/home/privateserver/.conda/envs/ldm/lib/python3.8/site-packages/torch/nn/functional.py", line 2044, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper__index_select)
```

**Comment by rinongal** [comment] 2022-09-21 06:38
@Baquara Just a few questions to make sure:

1) Did you directly clone this repo? Or another implementation?
2) Can you try running with ``--gpus 1`` and see if you get a different result?
3) For sanity, can you run: 

```
>>> import torch

>>> torch.cuda.is_available()
>>> torch.cuda.device_count()
```
and make sure that torch is seeing your GPU correctly?

**Comment by Baquara** [comment] 2022-09-21 06:53
> @Baquara Just a few questions to make sure:
> 
>     1. Did you directly clone this repo? Or another implementation?
> 
>     2. Can you try running with `--gpus 1` (no trailing comma) and see if you get a different result?
> 
>     3. For sanity, can you run:
> 
> 
> ```
> >>> import torch
> 
> >>> torch.cuda.is_available()
> >>> torch.cuda.device_count()
> ```
> 
> and make sure that torch is seeing your GPU correctly?


1 - Yes, this repo. No forks.

2 - I already tried that before, no changes unfortunately.

3 -  Sure:

```
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch.cuda.device_count()
1

```
